### PR TITLE
MODERN_DIAG_MANAGER: Fix cell measures attribute

### LINKED ISSUE #1814: BUG - MODERN DIAG MANAGER cell measures attribute is not written correctly
**Describe the bug**
As reported by Sergey, the cell measures attribute is not written correctly. This ncdump shows the problem:
```
        float area(time, grid_yt, grid_xt) ;
                area:long_name = "area in the grid cell" ;
                area:units = "m2" ;
                area:missing_value = -1.f ;
                area:_FillValue = -1.f ;
                area:ocean_fillvalue = 0. ;
                area:cell_methods = "area: sum time: point" ;
                area:coordinates = "geolon_t geolat_t" ;
...
        float bl(time, grid_yt, grid_xt) ;
                bl:long_name = "biomass of leaves" ;
                bl:units = "kg C/m2" ;
                bl:missing_value = -1.f ;
                bl:_FillValue = -1.f ;
                bl:cell_methods = "area: mean time: point" ;
                bl:cell_measures = "area: area_ntrl" ;
                bl:coordinates = "geolon_t geolat_t" ;
```
The cell measures should be "area" not "area_ntrl". The diag_table yaml has "area_ntrl" as the **variable name** and "area" as the **output name**. 

**To Reproduce**
These changes to the existing unit test will reproduce the issue:
https://github.com/uramirez8707/FMS/commit/5ca4c844e61926471c886d64c7d4876dd0a5911f
https://github.com/uramirez8707/FMS/actions/runs/20583117090/job/59114568361
``` FATAL: The cell_measures attribute is not the expected result! (area: area) vs (area: area_file2)```

**Expected behavior**
The test should not fail

**System Environment**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This PR fixes an issue when adding the cell_measures attribute. The code was not getting the output name of the area variable correctly.

https://github.com/NOAA-GFDL/FMS/blob/59763e905da2c855a753e2350c83017bde357295/diag_manager/fms_diag_field_object.F90#L816-L822
Fixes #1814 

**How Has This Been Tested?**
CI, including new test (which fails without this update)

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: diag_manager/fms_diag_field_object.F90 [hunk 1]
```diff
@@ -806,18 +806,31 @@ end function get_vartype
...
   character(len=:), allocatable :: rslt
+
+  integer :: i
+
   rslt = this%varname
 
   !< If writing the varname can be the outname which is defined in the yaml
   if (present(to_write)) then
     if (to_write) then
-    !TODO this is wrong
```
Comment (rem1776) [inline diag_manager/fms_diag_field_object.F90:819]: lol
