### PR TITLE
horiz_interp fixes for r4 tests

### LINKED ISSUE #1735: horiz_interp mixed precision issues
**Describe the bug**
theres a unfortunate typo in one of the CPP macros set in the makefile.am for test_horiz_interp:
https://github.com/NOAA-GFDL/FMS/blob/418b55dd82405889191dc8bb3813d492bc81b21b/test_fms/horiz_interp/Makefile.am#L39-L41

Since it was never discovered due to a default real size being set, some of the tests now fail when using r4 as intended, mostly due to unmodified floating point comparisons.

**To Reproduce**
fix the typo and run the horiz_interp tests

**Expected behavior**
fix the r4 implementations of these routines so the tests pass

**System Environment**
amd box

**Additional context**
came up working on https://github.com/NOAA-GFDL/pyFMS/pull/13

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Fixes the r4 tests to build properly (see issue below) and makes some adjustments in the code for when using kind 4 reals. Tolerances needed to be a bit large for the bicubic test in particular, not sure if thats just due to the algorithm.

Fixes #1735

**How Has This Been Tested?**
make distcheck on amd box

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: test_fms/horiz_interp/test_horiz_interp.F90 [hunk 1]
```diff
@@ -125,7 +120,13 @@ subroutine test_horiz_interp_spherical
...
     real(HI_TEST_KIND_) :: lat_dst_beg = -90._lkind,  lat_dst_end = 90._lkind
     real(HI_TEST_KIND_) :: D2R = real(PI,HI_TEST_KIND_)/180._lkind
-    real(HI_TEST_KIND_), parameter :: SMALL = 1.0e-10_lkind
+    real(HI_TEST_KIND_) :: tolerance
+
+    if(HI_TEST_KIND_ == r8_kind) then
+      tolerance = 1.0e-10_r8_kind
+    else
+      tolerance = 1.0e-5_r4_kind
+    endif
```
Comment (bensonr) [inline test_fms/horiz_interp/test_horiz_interp.F90]: Should these be `lkind` like the one it replace and those below @656-659

Comment (rem1776) [reply test_fms/horiz_interp/test_horiz_interp.F90]: yeah, should be fixed now: c223906

**Review by bensonr — APPROVED** [review]
