### PR TITLE
Fixed num_lines in mpp_util.inc to have the proper number of lines

### LINKED ISSUE #399: MPP function get_ascii_file_num_lines returns wrong value
**Describe the bug**
The MPP function get_ascii_file_num_lines returns a value that is one higher than the number of lines in the file. E.g. if there are 3 lines in an ASCII file, the function will return the value 4.

**To Reproduce**
Call the MPP function get_ascii_file_num_lines on an ASCII file with a known number of lines. E.g. run this sample program:

```
program test_get_ascii_lines
  use mpp_mod, only : get_ascii_file_num_lines, mpp_init, mpp_exit, INPUT_STR_LENGTH

  implicit none

  integer :: my_known_lines=5
  integer :: my_guess_lines_in_file
  character(len=10) :: file_5_line="ascii_5   " ! ascii_5 contents listed below the program

  call mpp_init()
  ! Check on 5 line file
  my_guess_lines_in_file = get_ascii_file_num_lines(trim(file_5_line), INPUT_STR_LENGTH)
  print *, "My Guess", my_guess_lines_in_file
  print *, "Known Lines", my_known_lines
  call mpp_exit()
end program test_get_ascii_lines
```

Contents of `ascii_5` file:
```
uno
dos
tres
quatro
cinco
```

**Expected behavior**
I expect the function to return the correct number of lines

**System Environment**
Describe the system environment, include:
- OS: Skylake Box
- Compiler(s): Intel 18
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI): Default
- netCDF Version: For both C and Fortran: Default
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
I'm looking at the function now, and I'm wondering whether or not num_lines should be 0 here instead of 1?

https://github.com/NOAA-GFDL/FMS/blob/e6fd03b070eb1ba8ffbca740fd69681ee16d6be7/mpp/include/mpp_util.inc#L1413

### PR DESCRIPTION
**Pull request by GFDL-Eric**
**Description**
Makes changes to num_lines in mpp_util.inc so that it accurately reflects the number of lines in the file (except when the file has no content, in which case num_lines will be 1). Also adds an option in ascii_read to output the lines_and_length parameter (useful for testing purposes mostly).

Fixes #399 

**How Has This Been Tested?**
Ran with Intel19 on Skylake. Modified test_read_ascii_data in test_fms/fms2_io to test for files with varying line quantities (have since reverted those test changes to the standard test).

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by wrongkindofdoctor — DISMISSED** [review]

**Comment by GFDL-Eric** [comment]
> Looks like it's failing the diag_manager test in the CI, maybe it's from GNU?

I still need to merge in what Rusty did (and obviously address this issue), so stay tuned?

**Review by wrongkindofdoctor — DISMISSED** [review]

File: fms2_io/fms_io_utils.F90 [hunk 1]
```diff
@@ -505,15 +505,17 @@ end subroutine open_check
 
 !> @brief Read the ascii text from filename `ascii_filename`into string array
 !! `ascii_var`
-subroutine ascii_read(ascii_filename, ascii_var)
+subroutine ascii_read(ascii_filename, ascii_var, out_dims)
   character(len=*), intent(in) :: ascii_filename !< The file name to be read
   character(len=:), dimension(:), allocatable, intent(out) :: ascii_var !< The
                                                                         !! string
                                                                         !! array
+  integer, dimension(2), optional, intent(out) :: out_dims
```
Comment (thomas-robinson) [inline fms2_io/fms_io_utils.F90:513]: This needs to be documented with doxygen comments

File: mpp/include/mpp_util.inc [hunk 2]
```diff
@@ -1533,6 +1541,7 @@ end function rarray_to_char
     integer :: status, i, f_unit, log_unit
     integer :: from_pe
     integer :: pnum_lines, num_lines
+    character(len=LENGTH) :: str_tmp
```
Comment (thomas-robinson) [inline mpp/include/mpp_util.inc:1544]: This variable needs to be documented

File: mpp/include/mpp_util.inc [hunk 3]
```diff
@@ -1574,9 +1583,13 @@ end function rarray_to_char
                    pnum_lines = 1
 
                    do
-                      read (UNIT=f_unit, FMT='(A)', IOSTAT=status) Content(pnum_lines)
+                      read (UNIT=f_unit, FMT='(A)', IOSTAT=status) str_tmp
```
Comment (thomas-robinson) [inline mpp/include/mpp_util.inc:1586]: If this is done more than once, then `str_tmp` should be allocatable and allocated/deallocated every time.  If `len_trim(str_tmp) == LENGTH` is true the first time, it will be true every time because you never cleared the buffer.

**Review by thomas-robinson — CHANGES_REQUESTED** [review]

**Review by wrongkindofdoctor — APPROVED** [review]

File: fms2_io/fms_io_utils.F90 [hunk 4]
```diff
@@ -510,8 +510,9 @@ subroutine ascii_read(ascii_filename, ascii_var, out_dims)
   character(len=:), dimension(:), allocatable, intent(out) :: ascii_var !< The
                                                                         !! string
                                                                         !! array
-  integer, dimension(2), optional, intent(out) :: out_dims
+  integer, dimension(2), optional, intent(out) :: out_dims !< Optional argument to return number of lines and max_length of file
```
Comment (thomas-robinson) [inline fms2_io/fms_io_utils.F90:513]: This is *ok*, but why not just have 2 different optional arguments (`number_of_lines` and `max_length_of_file`) instead of one array with two different pieces of information?

**Review by thomas-robinson — DISMISSED** [review]

**Review by rem1776 — APPROVED** [review]

**Review by thomas-robinson — APPROVED** [review]

**Review by wrongkindofdoctor — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

File: mpp/include/mpp_util.inc (hunk 3 above)
Comment (thomas-robinson) [reply mpp/include/mpp_util.inc:1586]: I tested this with intel and gfortran and it seems to work.
