### PR TITLE
Test script updates and input tests

### LINKED ISSUE #209: What is test issue that prevents tests from running on Darwin?
I believe someone explained it to me at one point, but I can't find the explanation, so I have to ask again...

What is the reason we see this in bats files?

```
setup () {
  if [ "x$(uname -s)" = "xDarwin" ]
  then
    skip_test=true
  else
    skip_test=false
  fi
}
```

What is it about Darwin that causes these tests to fail?

Instead of just identifying Darwin as the culprit, can we drill a little deeper to what actual feature is missing on Darwin? Then we can test for that feature in configure.ac, and use that to determine whether these tests can be run.

Also, I would expect that if Darwin breaks so many tests, that the code does not really work on Darwin. So instead of just turning off tests, maybe you should give the user an error message at configure time, saying that Darwin does not work?

### LINKED ISSUE #322: Make Check fails in skylake box
**Describe the bug**
Make check fails in test_mpp_domains2 with the following crash:

```
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to     131072.

FATAL from PE     1: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage

Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

FATAL from PE     0: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage

FATAL from PE     0: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage
```

**To Reproduce**
Fails this way specifically while testing pull request #310 in skylake with intel. 
With shell commands:
```
autoreconf -i 
 module load intel impi netcdf 
 ./configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc" 
 make check
```

**Expected behavior**
Make check should pass.

**System Environment**
Describe the system environment, include:
- OS: [Skylake Box
- Compiler(s): Intel2020
- MPI type, and version: impi2020
- netCDF Version: netcdf4.6.1
- Configure options:  FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"

**Additional context**
Reverting Pull #249 fixes the issue.

### LINKED ISSUE #357: Fix skipped mpp_pset tests
**Describe the bug**
The tests in test_mpp_pset2.sh are skipped, and when not skipped, may raise errors.

**To Reproduce**
Run make check of FMS after removing the skip command from test_mpp_pset2.sh.

**Expected behavior**
Unit tests should run as intended and pass.

**System Environment**

**Additional context**

### LINKED ISSUE #482: First time a test is skipped causes rest of tests in shell script to be skipped as well.
**Describe the bug**
We are using the keyword "skip" in our shell scripts to skip tests. This results in execution like this:

```
bash -x ./test_mpp_domains2.sh
+ . ../test_common.sh
++ set -e
++ TEST_PASS=0
++ TEST_FAIL=1
++ TEST_SKIP=77
++ TEST_ERROR=99
++ top_srcdir=/home/ed/f1
++ top_buildir=/home/ed/f1
++ mpi_launcher=mpirun
++ oversubscribe=
++ uname -s
+ '[' xLinux = xDarwin ']'
+ '[' x = xtrue ']'
+ echo '1: Test simple functionality'
1: Test simple functionality
+ run_test test_domains_simple 4
+ test x = xskip
+ test xmpirun '!=' x
+ npes='-n 4'
+ mpirun -n 4 ./test_domains_simple
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to    32768.
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to  4000000.
 pe, tile, ipos, jpos=           0           1           0           0  pearray(:,jpos)=           0           1  pearray(ipos,:)=           0           2
 pe, tile, ipos, jpos=           1           1           1           0  pearray(:,jpos)=           0           1  pearray(ipos,:)=           1           3
 pe, tile, ipos, jpos=           2           1           0           1  pearray(:,jpos)=           2           3  pearray(ipos,:)=           0           2
 pe, tile, ipos, jpos=           3           1           1           1  pearray(:,jpos)=           2           3  pearray(ipos,:)=           1           3
 MPP_DOMAINS_STACK high water mark=           0

Tabulating mpp_clock statistics across      4 PEs...

                                          tmin          tmax          tavg          tstd  tfrac grain pemin pemax
Total runtime                         0.000547      0.000548      0.000547      0.000000  0.999     0     0     3
 MPP_STACK high water mark=           0
+ run_test test_mpp_domains 2 skip
+ test xskip = xskip
+ return 77
```

Note that the first skipped test causes the shell script to return. That's because of this code in test_fms/test_common.sh:

```
# Set exit codes to control the failure modes.  These exit codes are found in
# The GNU Automake manual: https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html
# Note, any non-zero status, other than SKIP and ERROR is a FAIL
TEST_PASS=0
TEST_FAIL=1
TEST_SKIP=77
TEST_ERROR=99

run_test()
{
    # If the tests is known to fail exit
    if test "x${3}" = "xskip" ; then
        return $TEST_SKIP
    else
        # If there is no mpi launcher just ./{job_script}
        if test "x$mpi_launcher" != "x" ; then
            npes="-n ${2}"
        fi
    fi

    # Run test
    $mpi_launcher $oversubscribe $npes ./${1}
}
```

So you think you are skipping just one test, but you are skipping all the remaining tests in the shell script.

**To Reproduce**
Run any of the test scripts which skip tests, using bash -x.

**Expected behavior**
I expected the test to be skipped, but subsequent tests to run.

Given that the first skip causes all remaining tests in the shell script to be skipped as well, perhaps we want to comment out tests, instead of skipping them.

**System Environment**
I'm on a GNU/Linux system.

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

### LINKED ISSUE #484: Enable mpp_domains tests in test_fms/mpp
**Describe the bug**
Because of #482 all tests in test_mpp_domains2.sh are skipped.

**To Reproduce**
Use autotools build and run make check and look at the test_fms/mpp/test_mpp_domains2.sh.log 

**Expected behavior**
Tests that can be correctly executed should be.

**System Environment**
All

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Was gonna make this off of the branch from #654 , but figured it might be better to make a separate PR since the comparison was huge with the updates to FMS.

- takes Seth's updates from #654 and converts each test script to use the new harness
- Adds environment variables for verbose test output when set (TEST_VERBOSE) 
- Adjusts logic so SKIP_TESTS can be used with two digit test numbers and ranges
- Adds in/fixes some tests that were in PRs or skipped previously
- Adds a configure flag, `--enable-test-input=/path`, that enables tests in FMS that require input files. The input directory and structure it needs to be in is on both dev boxes at /home/fms_test_input

Fixes #209 
Fixes #322 
Fixes #482 
Fixes #484 

**How Has This Been Tested?**
Tested on amd and skylake with intel and gnu compilers

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by wrongkindofdoctor — DISMISSED** [review]

File: mosaic/read_mosaic.c [hunk 1]
```diff
@@ -259,13 +259,13 @@ void get_var_data(const char *file, const char *name, void *data)
   switch (vartype) {
     case NC_DOUBLE:case NC_FLOAT:
 #ifdef OVERLOAD_R4
-      status = nc_get_var_float(ncid, varid, data);
+      status = nc_get_var_float(ncid, varid, (float *)data);
```
Comment (bensonr) [inline mosaic/read_mosaic.c:262]: Is this OVERLOAD potentially affecting how things work and should the NC_DOUBLE and NC_FLOAT cases be broken into individual cases?

File: mosaic/read_mosaic.c [hunk 2]
```diff
@@ -319,13 +319,13 @@ void get_var_data_region(const char *file, const char *name, const size_t *start
   switch (vartype) {
     case NC_DOUBLE:case NC_FLOAT:
 #ifdef OVERLOAD_R4
-      status = nc_get_vara_float(ncid, varid, start, nread, data);
+      status = nc_get_vara_float(ncid, varid, start, nread, (float *)data);
```
Comment (bensonr) [inline mosaic/read_mosaic.c:322]: Same as above

File: test_fms/drifters/test_drifters_comm.F90 [hunk 3]
```diff
@@ -59,6 +59,7 @@ program test_drifters_comm
 
   ! read input
   read (input_nml_file, drifters_comm_nml, iostat=io_status)
+  if(io_status > 0) call mpp_error(FATAL, 'test_drifters_comm: Error reading input.nml')
```
Comment (bensonr) [inline test_fms/drifters/test_drifters_comm.F90:62]: Shouldn't we be using fms_mod::check_nml_error here?

File: test_fms/mpp/test_domains_utility_mod.F90 [hunk 4]
```diff
@@ -71,12 +72,12 @@ subroutine fill_coarse_data_r8(data, rotate, iadd, jadd, is_c, ie_c, js_c, je_c,
...
           do j = js_c, je_c+jshift
              do i = is_c, ie_c+ishift
-                data(i,j,k) = sign2*((j+iadd)*1.e+6 + (ny-i+1+jadd+ishift)*1.e+3 + k + y_add)
+                rdata(i,j,k) = sign2*( dble(j+iadd)*1.d+6 + dble(ny-i+1+jadd+ishift)*1.d+3 + dble(k) + y_add)
              enddo
           enddo
        enddo
     case default
-       call mpp_error(FATAL,"fill_coarse_data: rotate_coarse must be ZERO, NINETY, MINUS_NINETY")
+       call mpp_error(FATAL,"fill_coarse_rdata: rotate_coarse must be ZERO, NINETY, MINUS_NINETY")
```
Comment (bensonr) [inline test_fms/mpp/test_domains_utility_mod.F90:80]: Should this be "fill_coarse_data_r8"?

File: test_fms/mpp/test_domains_utility_mod.F90 [hunk 5]
```diff
@@ -37,11 +38,11 @@ module test_domains_utility_mod
 
   contains
 
-subroutine fill_coarse_data_r8(data, rotate, iadd, jadd, is_c, ie_c, js_c, je_c, nz, isd, jsd, nx, ny, &
+subroutine fill_coarse_data_r8(rdata, rotate, iadd, jadd, is_c, ie_c, js_c, je_c, nz, isd, jsd, nx, ny, &
```
Comment (bensonr) [inline test_fms/mpp/test_domains_utility_mod.F90:41]: Don't see the need to change this from data to rdata as it's local to the routine.

File: test_fms/mpp/test_mpp_domains.F90 [hunk 6]
```diff
@@ -50,7 +50,12 @@ program test_mpp_domains
   use mpp_domains_mod, only : mpp_group_update_type, mpp_create_group_update
   use mpp_domains_mod, only : mpp_do_group_update, mpp_clear_group_update
   use mpp_domains_mod, only : mpp_start_group_update, mpp_complete_group_update
-  use mpp_domains_mod, only : WUPDATE, SUPDATE, mpp_get_compute_domains, NONSYMEDGEUPDATE, mpp_get_tile_id
+  use mpp_domains_mod, only : WUPDATE, SUPDATE, mpp_get_compute_domains, &
+                              NONSYMEDGEUPDATE, mpp_get_tile_id
+  use mpp_domains_mod, only : WUPDATE, SUPDATE, mpp_get_compute_domains, NONSYMEDGEUPDATE
```
Comment (bensonr) [inline test_fms/mpp/test_mpp_domains.F90:55]: Remove duplicates.

File: test_fms/mpp_io/test_mpp_io.F90 [hunk 7]
```diff
@@ -84,24 +81,11 @@ program test
...
-  close(unit)
-#endif
-
-      if (io_status > 0) then
-         call mpp_error(FATAL,'=>test_mpp_io: Error reading input.nml')
-      endif
 
+  if (io_status > 0) then
+    call mpp_error(FATAL,'=>test_mpp_io: Error reading input.nml')
+  endif
```
Comment (bensonr) [inline test_fms/mpp_io/test_mpp_io.F90:88]: Use check_nml_error.

**Review by bensonr — COMMENTED** [review]
Nice job breaking up the mpp_domains test into easier to handle individual tests.

File: mosaic/read_mosaic.c (hunk 1 above)
Comment (rem1776) [reply mosaic/read_mosaic.c:262]: These changes were put in by seth in #654 actually to fix some compile issues on darwin, but they look good to me. With the previous logic it would read in data as float or double based on whichever is the fortran default kind so this just adds the cast to data since its a void pointer.

File: test_fms/mpp_io/test_mpp_io.F90 (hunk 7 above)
Comment (rem1776) [reply test_fms/mpp_io/test_mpp_io.F90]: updated in 7291341

File: test_fms/mpp_io/test_io_mosaic_R4_R8.F90 [hunk 8]
```diff
@@ -95,9 +92,9 @@ program test_io_mosaic_R4_R8
   read( unit,test_io_mosaic_nml, iostat=io_status )
   close(unit)
 
-      if (io_status > 0) then
-         call mpp_error(FATAL,'=>test_io_mosaic_R4_R8: Error reading input.nml')
-      endif
+  if (io_status > 0) then
+    call mpp_error(FATAL,'=>test_io_mosaic_R4_R8: Error reading input.nml')
+  endif
```
[the remark this answers is not in the document]
Comment (rem1776) [reply test_fms/mpp_io/test_io_mosaic_R4_R8.F90]: updated with the right read statement in 7291341

File: test_fms/mpp/test_mpp_domains.F90 (hunk 6 above)
Comment (rem1776) [reply test_fms/mpp/test_mpp_domains.F90]: done in 7291341

File: test_fms/mpp/test_domains_utility_mod.F90 (hunk 5 above)
Comment (rem1776) [reply test_fms/mpp/test_domains_utility_mod.F90]: not sure why i did that in the first place.. its changed back now

File: test_fms/mpp/test_domains_utility_mod.F90 (hunk 4 above)
Comment (rem1776) [reply test_fms/mpp/test_domains_utility_mod.F90]: Yes fixed this and the r4 message as well

File: test_fms/drifters/test_drifters_comm.F90 (hunk 3 above)
Comment (rem1776) [reply test_fms/drifters/test_drifters_comm.F90]: fixed in 7291341

**Comment by rem1776** [comment]
@bensonr This should be ready now, I put in fixes for everything but the mosaic changes

**Review by bensonr — APPROVED** [review]

**Review by thomas-robinson — APPROVED** [review]
