### PR TITLE
Fix data_override so that PGI (and related compilers) are happy

### LINKED ISSUE #612: PGI (and aocc) imported subroutines conflicting names
**Describe the bug**
In data_override, the modules time_interp_external and time_interp_external2 are used, with the functions and subroutines from time_interp_external remapped to a different name to avoid conflicts (e.g. get_external_field_classic => get_external_field). However, it appears that the functions and subroutines from time_interp_external2 must also be remapped (e.g. get_external_field_new => get_external_field) to avoid a crash with PGI and related compilers like aocc. 

**To Reproduce**
Compile any flavor of 2020.04 of FMS with your favorite PGI compiler

**Expected behavior**
Don't crash plz

**System Environment**
Gaea, amd, skylake

**Additional context**
Maybe PGI needs more Intel magic? 
image

### PR DESCRIPTION
**Pull request by GFDL-Eric**
**Description**
Remaps the subroutines and functions from time_interp_external2 in the following manner:
get_external_field_new => get_external_field

This addresses an issue in PGI and aocc compilations wherein a crash occurs when e.g. get_external_field_classic => get_external_field is used from time_interp_external but get_external_field is also used from time_interp_external2

Fixes #612 

**How Has This Been Tested?**
Skylake compilation, aocc compilation on amd, gaea tests with MOM6 test runs

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: data_override/data_override.F90 [hunk 1]
```diff
@@ -30,10 +30,13 @@ module data_override_mod
...
                                    set_override_region_classic=>set_override_region, &
                                    reset_src_data_region_classic=>reset_src_data_region
-use time_interp_external2_mod, only:time_interp_external_init, time_interp_external, &
-                                   init_external_field, get_external_field_size, &
+use time_interp_external2_mod, only:time_interp_external_init_new=>time_interp_external_init, &
+                                   time_interp_external_new=>time_interp_external, &
+                                   init_external_field_new=>init_external_field, &
+                                   get_external_field_size_new=>get_external_field_size, &
+                                   set_override_region_new=>set_override_region, &
+                                   reset_src_data_region_new=>reset_src_data_region, &
```
Comment (thomas-robinson) [inline data_override/data_override.F90:38]: *new* it too relative.  If this works with fms2io, why not use that instead of "new"?

Comment (GFDL-Eric) [reply data_override/data_override.F90]: updated in d794967226b7c7dc20e8b7ea6a8890cdd7c39478

**Review by thomas-robinson — APPROVED** [review]
