### PR TITLE
Correct Fortran STOP statement in mpp test programs

### LINKED ISSUE #305: test_mpp_memuse.F90 error
**Describe the bug**
When I run a `make check` with an intel compiler, I encounter the following error:
```
test_mpp_memuse.F90(133): error #6345: Either a PAUSE, STOP or ERROR STOP statement has an invalid argument.   [RETURN_VAL]
  stop return_val
-------^
```

**To Reproduce**
On the lscsky50-d 
```bash
module load intel/2019_up2 impi/2019_up2 netcdf/4.6.1
autoreconf -i
./configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"
make check
```

**Expected behavior**
This test should compile

**System Environment**
Describe the system environment, include:
- OS: 
- Compiler(s): intel19
- MPI type, and version: impi
- netCDF Version: 4.6.1
- Configure options: FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"

**Additional context**
The git hash I'm using is 7788b781ac4e7fecf0d6cebc239206242305ac36

### PR DESCRIPTION
**Pull request by underwoo**
**Description**
The Fortran STOP statement only accepts constant integers and characters, according to the standard.  gfortran ignores that part of the standard.  This commit corrects two Fortran STOP statements in mpp test programs.

Fixes #305 

**How Has This Been Tested?**
Tested fix on Mac OS with openMPI, and an Intel Skylake box using Intel's MPI

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: test_fms/mpp/test_mpp_mem_dump.F90 [hunk 1]
```diff
@@ -32,13 +32,10 @@ program test_mpp_mem_dump
...
 
   call mpp_mem_dump(memuse)
 
   if (memuse .LT. 0.0) then
-    return_val = 1
+    stop "mpp_mem_dump return negative value for memory"
   endif
-
-  stop return_val
 end program test_mpp_mem_dump
```
Comment (thomas-robinson) [inline test_fms/mpp/test_mpp_mem_dump.F90]: If you want to return an integer, why not just wrap `stop` statement in the if block
```fortran
if (memuse .LT. 0.0) then		￼  
￼    stop 1		￼    
￼endif
```
Or use parameter integers to do the same thing and always stop with a value
```fortran
integer, parameter :: return_error = 1
integer, parameter :: return_success = 0
...
if (memuse .LT. 0.0) then
￼    stop return_error
else
    stop return_success
endif
```

Comment (underwoo) [reply test_fms/mpp/test_mpp_mem_dump.F90]: The value of the return is not important, other than it _must_ be non-zero.  Adding the character constant will have `STOP` end with a non-zero, I just don't get to choose the value of the exit.
