### PR TITLE
Data override fix

### LINKED ISSUE #514: Data_override[2] crash: NetCDF: Index exceeds dimension bound
**Describe the bug**
The ufs-s2s-model with MOM6 crashes in data_override: 
```
159: FATAL from PE     9: NetCDF: Index exceeds dimension bound
159: fcst.exe           00000000018E5904  Unknown               Unknown  Unknown
159: fcst.exe           0000000000951819  mom_surface_forci         439  mom_surface_forcing_nuopc.F90
159: fcst.exe           00000000006EB42A  mom_ocean_model_n         514  mom_ocean_model_nuopc.F90
159: fcst.exe           00000000006BE144  mom_cap_mod_mp_mo        1452  mom_cap.F90
```

where line439 is 
``` 
 if (associated(IOB%lrunoff)) then
      if(CS%liquid_runoff_from_data)call data_override('OCN', 'runoff', IOB%lrunoff, Time)
  Endif
```

and this data_table
```
"OCN", "runoff", "runoff", "./INPUT/runoff.daitren.clim.1440x1080.v20180328.nc", "none" ,  1.0
```
This crash happens because the `IOB%lrunoff` variable is the size of the data_domain (which contains halos) and this is an 'ongrid' case. Data_override tries to read in the data from the file (where the data in the file is the size of the compute domain) into`IOB%lrunoff` so the code crashes because it is not the same size. 

**To Reproduce**
I created a unit case that: 
1. Creates a domain with halos
2. Allocated a buffer to be the size of the compute domain 
3. Calls `data_override_init` with the domain, and then `data_override`
The test was set up to use the file/grid/data_table as in the ufs-s2s-model. 

**Expected behavior**
The unit test should work. Nothing should be "overridden" into the 'halo' part of the buffer as it was done in data_override[1].  

**System Environment**
Describe the system environment, include:
This happens in any system ... 

**Additional context**
...

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This PR: 

1. Removes `#include <fms_platform.h>` to fix the line number when running in the debugger
2. Modifies logic in data_override so that if the data is `ongrid` and you are not in the compute domain, you only send in the compute domain portion of the buffer. 

Fixes #514 

**How Has This Been Tested?**
With my unit test in GAEA with intel18 on c4. 
Passes travis. 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included **[Test requires input netcdf files]**
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
fyi @GFDL-Eric @menzel-gfdl

**Comment by edwardhartnett** [comment]
How come there are no tests or test changes to go with this?

File: test_fms/data_override/test_data_override2.sh [hunk 1]
```diff
@@ -23,21 +23,29 @@
...
+#tnum=$( printf "%2.2d" 1 )
+#sed "s/<test_num>/${tnum}/"  $top_srcdir/test_fms/data_override/input_base.nml > input.nml
+#run_test test_data_override 2 skip
 
-tnum=$( printf "%2.2d" 2 )
-sed "s/<test_num>/${tnum}/"  $top_srcdir/test_fms/data_override/input_base.nml > input.nml
-run_test test_data_override 2 skip
+#tnum=$( printf "%2.2d" 2 )
+#sed "s/<test_num>/${tnum}/"  $top_srcdir/test_fms/data_override/input_base.nml > input.nml
+#run_test test_data_override 2 skip
```
Comment (thomas-robinson) [inline test_fms/data_override/test_data_override2.sh:50]: Is this test obsolete?  It's completely commented out.  Why not just delete?

Comment (uramirez8707) [reply test_fms/data_override/test_data_override2.sh:50]: It is commented out because it doesn't run and it doesn't run because there are input netcdf files missing. 
It tests something different than the test I added.

Comment (thomas-robinson) [reply test_fms/data_override/test_data_override2.sh:50]: OK, so it's there for the future then?

Comment (uramirez8707) [reply test_fms/data_override/test_data_override2.sh:50]: yes
