### PR TITLE
Fixing issue 383 - Axes for reginal diagnostics not written corrrectly.

### LINKED ISSUE #383: Axis for regional diagnostics are not written correctly
**Describe the bug**
The axis for regional diagnostics are not written correctly. 
Each of the cores that are writing the regional diagnostics are writing the whole region instead of their own chunk. 

**To Reproduce**
Run @nikizadehgfdl  OMIP run with 442 cores and regional diagnostics. 

The regional variable `volcello` is written by 8 cores, each core writes their own file (`19480101.ocean_Agulhas_section.nc.XXXX`). 
If you run with current master, in each file the yaxis has a size of 132. 

But if you run with **xanadu** code: 
In each file the yaxis has a size of {16,18,18,18,18,18,18,8}
(which totals 132)

The end file (after it is combined in fre, `19480101.ocean_Agulhas_section.nc`) is exactly (bitwise) the same as `19480101.ocean_Agulhas_section.nc.0001`. 

But you compared the end file with Xanadu's, the answers are "different" for points that are outside the chunk of the first core (for all y's greater than 16). 

**Expected behavior**
Behavior should be the same as *Xanadu* code

**System Environment**
Describe the system environment, include:
This happens in any system.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ngs333**
Modified diag_output.F90:write_axis_meta_data() to call
mpp_get_data_domain() function to get information to calculate
the start and end indecies of regional axes.
Fixes #383

**How Has This Been Tested?**
Xanadu run of MOM6  with regional diagnostics run and compared to new code.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@uramirez8707 and @nikizadehgfdl please test this

File: diag_manager/diag_output.F90 [hunk 1]
```diff
@@ -315,6 +316,8 @@ SUBROUTINE write_axis_meta_data(file_unit, axes, fileob, time_ops, time_axis_reg
     integer                                    :: id_axis_current
     logical :: is_time_axis_registered
     integer :: istart, iend
+    integer :: gstart, dgnd, cstart, cend !< Start and end of global and compute domains
```
Comment (bensonr) [inline diag_manager/diag_output.F90:319]: You define dgnd here, but it doesn't seem to get used.

File: diag_manager/diag_output.F90 [hunk 2]
```diff
@@ -383,9 +386,11 @@ SUBROUTINE write_axis_meta_data(file_unit, axes, fileob, time_ops, time_axis_reg
                          call write_data(fptr, axis_name, axis_data(istart:iend) )
                       endif
                     type is (FmsNetcdfFile_t) !< For regional X and Y axes, treat as any other axis
-                         call register_axis(fptr, axis_name, dimension_length=size(axis_data))
-                         istart = lbound(axis_data,1)
-                         iend = ubound(axis_data,1)
+                         call mpp_get_global_domain(domain, gstart, gend, glength)  !< Get the global indicies
+                         call mpp_get_compute_domain(domain, cstart, cend, clength) !< Get the compute indicies
```
Comment (bensonr) [inline diag_manager/diag_output.F90:390]: I believe these interfaces have a lot of optional argument references.  You should refer to the optional arguments with XXX=YYY.

The variable "gend" was already defined for use with a "gbegin" pair.  Are you using "gend" here safely?

File: diag_manager/diag_output.F90 (hunk 1 above)
Comment (thomas-robinson) [reply diag_manager/diag_output.F90:319]: `dgnd` should be `gend`

File: diag_manager/diag_output.F90 (hunk 2 above)
Comment (thomas-robinson) [reply diag_manager/diag_output.F90:390]: It should be able to be used here because it is redefined where it's used later.  I guess I didn't realize it, though.  @ngs333 should probable change the name of these variables.

File: diag_manager/diag_output.F90 (hunk 1 above)
Comment (thomas-robinson) [reply diag_manager/diag_output.F90:319]: ... which would cause an issue because there already is a `gend`
