### PR TITLE
Fix some errors find by Address Sanitizer 

### LINKED ISSUE #1803: `mpp_check_field_2d_type1` has use after free
**Describe the bug**

In the following fragment, deallocation happens right after usage, however, since, `mpp_send` does not have mpp_sync inside of the call, actual data send may happen at any time before `mpp_sync`. So, deallocation between these two points is not safe.

`mpp_send`:
https://github.com/NOAA-GFDL/FMS/blob/f13435f7a23f24d9eebcf01ca520cd67851b087b/mpp/include/mpp_domains_misc.inc#L338-L339

`sync` point:
https://github.com/NOAA-GFDL/FMS/blob/f13435f7a23f24d9eebcf01ca520cd67851b087b/mpp/include/mpp_domains_misc.inc#L379

It was detected with AddressSanitizer.

**To Reproduce**
Compile and run tests with -fsanitize=address.

**Expected behavior**
No ASan error.

**System Environment**
Describe the system environment, include:
- OS: I do not remember
- Compiler(s): GCC 14.?.?
- MPI type, and version ???
- netCDF Version: 4.9.3
- Configure options: FFLAGS="-fsanitize=address", LDFLAGS="-fsanitize=address"

### LINKED ISSUE #1804: `test_xgrid` keeps local temporaries (use after free)
**Describe the bug**

In the following fragment, local temporaries `atm_data_in+K` are used for putting them on grid:
https://github.com/NOAA-GFDL/FMS/blob/f13435f7a23f24d9eebcf01ca520cd67851b087b/test_fms/exchange/test_xgrid.F90#L918-L921
`put_on_xgrid`, internally, keeps pointers to these local temporaries and uses them for some updating at:
https://github.com/NOAA-GFDL/FMS/blob/f13435f7a23f24d9eebcf01ca520cd67851b087b/test_fms/exchange/test_xgrid.F90#L921
`complete=.true.` routes when the updating should happen.

However, actual generated code is (some Fortran-like pseudocode):

```Fortran
    call put_to_xgrid(atm_data_in, 'ATM', x_1, Xmap, remap_method=remap_method)
    allocate(local_tmp1(shape(atm_data_in))
    local_tmp1 = atm_data_in + 1
    call put_to_xgrid(local_tmp1, 'ATM', x_2, Xmap, remap_method=remap_method, complete=.false.)
    deallocate (local_tmp1)
    allocate(local_tmp2(shape(atm_data_in))
    local_tmp2 = atm_data_in + 2
    call put_to_xgrid(local_tmp2, 'ATM', x_3, Xmap, remap_method=remap_method, complete=.false.)
    deallocate (local_tmp2)
    allocate(local_tmp3(shape(atm_data_in))
    local_tmp3 = atm_data_in + 3
    call put_to_xgrid(local_tmp3, 'ATM', x_4, Xmap, remap_method=remap_method, complete=.true.)
    deallocate (local_tmp3)
```

So, at `compete=true`, app uses already deallocated memory of `local_tmp1` and `local_tmp2`.

**To Reproduce**
Compile with `-fsanitize=address` and run tests
 
**Expected behavior**
No ASan errors.

**System Environment**
See FMS CI setup

**Additional context**
I've raised ASan errors in CI of this repo via modifing FFLAGS and LDFLAGS.

### LINKED ISSUE #1805: `test_diag_update_manager`: wrong datatype is set with `-fdefault-real-8`
**Describe the bug**

Here,
https://github.com/NOAA-GFDL/FMS/blob/f13435f7a23f24d9eebcf01ca520cd67851b087b/test_fms/diag_manager/test_diag_update_buffer.F90#L186
`missvalue` gets FP value of default real kind. `missvalue` has a constrain on type which can be only `integer(8)` or `real(4)`. So, once one uses default real kind as `real(8)`, the data with wrong length (8 bytes) is copied into `missvalue` which is 4 bytes long (once it is real), and, then, extra 4 bytes are written out of bounds.

Such errors can be easily detected with AddressSanitizer (ASan) and, actually, detected in this way.

**To Reproduce**
Enable ASan in CI.

**Expected behavior**
No ASan error

**System Environment**
CI of libFMS; FFLAGS="-fsanitize=address", LDFLAGS="-fsanitize=address"

### PR DESCRIPTION
**Pull request by foxtran**
**Description**
AddressSanitizer detected some errors which I've fixed here:
- `mpp_domain_misc`: `mpp_send` is non-blocking operation so, `send_buffer` must be alive at least until sync point. (Closes #1803)
- `mpp_utils_mpi`: in-place writing may give errors (not sure that it really happens here, but anyway)
- `test_diag_update_buffeer`: `-fdefault-real-8` generates `1.0e-5` as `real(8)`. Then, `real(8)` constructor of `missvalue` is called while it is `real(4)`. So, 4 extra bytes were written. (Closes #1805)
- `test_xgrid`: `put_to_xgrid` kept address of local/temporary variables generated by `array + x` expressions. Now, lifetimes of `array + x` arrays are expanded. That is why after #1778 there is a lot failures of CI. (Closes #1804)

**How Has This Been Tested?**
Tested in CI with AddressSanitizer. Unfortunately, not all Address Sanitizer errors are fixed. 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by uramirez8707 — APPROVED** [review]
Thank you for fixing these.

File: test_fms/diag_manager/test_diag_update_buffer.F90 [hunk 1]
```diff
@@ -183,7 +183,7 @@ program test_diag_update_buffer
    diag_field_id = 1
    sample = 1
    weight = 1.0
-   missvalue = 1.0e-5
+   missvalue = 1.0e-5_r4_kind
```
Comment (bensonr) [inline test_fms/diag_manager/test_diag_update_buffer.F90:186]: I know you aren't the original author here, but I see a deeper problem with the chosen assignment value.  At line 150, there is the possibility for missvalue to be typed as an i8 and associated with an i8 pointer leading to an invalid value.

**Comment by foxtran** [comment]
@uramirez8707, can it be merged?

**Review by rem1776 — APPROVED** [review]

**Review by bensonr — COMMENTED** [review]
My apologies.  While I performed the review shortly after the PR was entered, I see I never formally submitted it.  Please see my comment regarding the chosen missing value.

File: test_fms/diag_manager/test_diag_update_buffer.F90 (hunk 1 above)
Comment (foxtran) [reply test_fms/diag_manager/test_diag_update_buffer.F90:186]: As I understood, missvalue can be both real(4) or integer(8). So, this assignment can change type of missvalue that invalidates `missval_i8_ptr`, defined at line 150, although data still be accessible via `missval_i8_ptr`.

Comment (foxtran) [reply test_fms/diag_manager/test_diag_update_buffer.F90:186]: There is a shorter example how does it work: https://godbolt.org/z/5jW4P9oY4

**Review by bensonr — APPROVED** [review]
