### PR TITLE
diag_yaml update

### LINKED ISSUE #900: diag_yaml bugs
**Describe the bug**
1. `check_file_freq` crashes if the freq read in from a diag_table.yaml is less than 1 claiming that is not valid. However a frequency of 0 and -1 are allowed. 
https://github.com/NOAA-GFDL/FMS/blob/2c218d0aabd5340bde8f157d15ade6efd128e163/diag_manager/fms_diag_yaml.F90#L381-L382
https://github.com/NOAA-GFDL/FMS/blob/2c218d0aabd5340bde8f157d15ade6efd128e163/diag_manager/diag_table.F90#L79-L86

2. `check_field_reduction` tries to use specific indices to determine the reduction method. 
https://github.com/NOAA-GFDL/FMS/blob/2c218d0aabd5340bde8f157d15ade6efd128e163/diag_manager/fms_diag_yaml.F90#L471
However if your reduction method is something like "none" it will cause the crash:
``` 
forrtl: severe (408): fort: (4): Variable FIELD has substring ending point 7 which is greater than the variable length of 4
```

**To Reproduce**
Try to run diag_manager_init with a frequency of -1 or 0 and the code will crash. 
Try to run diag_manager_init with a reduction_method of "none" and the code will crash (in debug mode)

**Expected behavior**
-1 and 0 need to be accepted as valid frequencies. 
The reduction_method needs to be determined correctly. 

**System Environment**
Describe the system environment, include:
This happens in any system. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
Fix issue checking if frequency is valid.
Fix reading the diurnal and pow reduction

Fixes #900 

**How Has This Been Tested?**
`make check` passes

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: diag_manager/fms_diag_yaml.F90 [hunk 1]
```diff
@@ -484,8 +484,8 @@ function get_total_num_vars(diag_yaml_id, diag_file_ids) &
 subroutine check_file_freq(fileobj)
   type(diagYamlFiles_type), intent(inout) :: fileobj      !< diagYamlFiles_type obj to check
 
-  if (fileobj%file_freq < 1 ) &
-    call mpp_error(FATAL, "freq must be greater than 0. &
+  if (fileobj%file_freq < -1 ) &
+    call mpp_error(FATAL, "freq must be greater than -1. &
```
Comment (thomas-robinson) [inline diag_manager/fms_diag_yaml.F90:488]: This checks if `fileobj%file_freq` is less than -1.  If it IS -1, then this will be false.  Your error message says that it must be greater than -1.
Either this should be
```fortran
if (.not.(fileobj%file_freq > -1)) 
```
or your error message needs to be changed.

**Review by thomas-robinson — CHANGES_REQUESTED** [review]

File: diag_manager/fms_diag_yaml.F90 (hunk 1 above)
Comment (uramirez8707) [reply diag_manager/fms_diag_yaml.F90]: I changed it to: 
https://github.com/NOAA-GFDL/FMS/blob/011145d0ae844d01b7f1a474d8420ba3cd803137/diag_manager/fms_diag_yaml.F90#L487-L488

If the file_freq is not greater than on equal to -1, it should fail because freq must be greater than or equal to -1. 
It is easier to read. 

-1 is a valid freq: 
https://github.com/NOAA-GFDL/FMS/blob/2c218d0aabd5340bde8f157d15ade6efd128e163/diag_manager/diag_table.F90#L79-L86

**Review by thomas-robinson — APPROVED** [review]
