### PR TITLE
Fixes for style in fms2_io

### LINKED ISSUE #264: fms2_io/fms_io_utils.F90 exposes all internal and `use`d interfaces and variables
**Describe the bug**
The `fms2_io/fms_io_utils.F90` does not have a `private` statement to set the default sharing of the module variables and routines to private.  This exposes all of the modules own variables and any variables/routine included via the Fortran `use` statements.

`fms2_io/fms_io_utils.F90` also does not have `implicit none`.  This should be added when fixing the other bug.

**To Reproduce**
Comment out the `use, intrinsic :: iso_fortran_env` from the other files in the `fms2_io` directory, and build the library.  All files will still be able to compile.

**Expected behavior**
Removing `use, intrinsic :: iso_fortran_env` from the other files in the `fms2_io` directory should cause those files to not build, due to missing variable definitions for `int32`, `int64`, `real32` and/or `real64`.

**System Environment**
This was discovered on a Mac running 10.12.6, with homebrew version of gfortran, gcc.  All versions at homebrew's latest.

### PR DESCRIPTION
**Pull request by thomas-robinson**
---
name: Fixes for style in fms2_io
about: Adds `implicit none` and private to fms_io_utils.F90
title: ''
labels: ''
---

**Description**
The file fms_io_utils.F90 did not have `implicit none` or `private`, so I added them.  I had to make some routines `public` and fix blackboxio.F90 to because fms_io_utils.F90 was exposing things it shouldn't have been.
Fixes #264 

**How Has This Been Tested?**
I ran c96L33_am4p0_cmip6Diag in the AWG XML with xanadu code, master FMS, and my updates. It also passed the travis-ci check.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: fms2_io/fms_io_utils.F90 [hunk 1]
```diff
@@ -25,7 +26,8 @@ module fms_io_utils_mod
 public :: get_data_type_string
 public :: get_checksum
 public :: open_check
-
+public :: string_compare
+public :: restart_filepath_mangle
```
Comment (underwoo) [inline fms2_io/fms_io_utils.F90]: The `@internal` in the doxygen documentation for `restart_filepath_mangle` should also be removed.
