### PR TITLE
Fix test_read_input_nml2 failure and test_diag_update_buffer.F90 seg fault : Cray

### LINKED ISSUE #1300: test_read_input_nml2 fail and test_diag_update_buffer.F90 segfault : Cray
**Describe the bug**
Tests in test_read_input_nml2 fail with a FATAL message: "data resident in ./input.nml does not match that read into input_nml_file by read_input_nml"

diag_manager make check will not work because it fails to compile test_diag_update_buffer.F90 stating a segmentation fault.

**To Reproduce**
do a make check to run unit tests

**Expected behavior**
tests pass

**System Environment**
C5 
cce/15.0.1
cray-hdf5/1.12.2.3
cray-netcdf/4.9.0.3

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by laurenchilutti**
**Description**

Cray uses an IOSTAT of -4001 for end of file while other compilers typically use -1.  Because of this, the do loop (shown below) will not exit on the condition `if (stat.eq.-1)` at Line 71

https://github.com/NOAA-GFDL/FMS/blob/2be8aa452ad3e5f43e92c38a64f12d1ae6c43fb8/test_fms/mpp/test_read_input_nml.F90#L68-L79

To fix: I took the approach seen in fortran standards (section 12.11.5 in the [J3/23-007draft spec](https://j3-fortran.org/doc/year/23/23-007.pdf)) and replaced `if (stat.eq.-1)` with `if (stat < 0)` to check for end of file and exit loop.

I also noticed that the tests were not matching the description here:
https://github.com/NOAA-GFDL/FMS/blob/2be8aa452ad3e5f43e92c38a64f12d1ae6c43fb8/test_fms/mpp/test_read_input_nml.F90#L51-L56

Previously, test 1 was reading a blank input.nml and test 2 was reading a blank input_alternate.nml.  I have modified this so that there is data inside of input.nml and input_alternate.nml.  Test 4 still tests a blank nml with the name input_blank.nml

Cray was failing to compile test_diag_update_buffer.F90 because of the `1` at the beginning of line 289
https://github.com/NOAA-GFDL/FMS/blob/2be8aa452ad3e5f43e92c38a64f12d1ae6c43fb8/test_fms/diag_manager/test_diag_update_buffer.F90#L288-L290

I have removed the `1` and refactored the code a little bit - I am open to feedback on the changes I made and will undo if they are not helpful.

Fixes #1300 

**How Has This Been Tested?**
make and make check on 
C5
cce/15.0.1
cray-hdf5/1.12.2.3
cray-netcdf/4.9.0.3

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: test_fms/mpp/test_read_input_nml.F90 [hunk 1]
```diff
@@ -68,7 +68,7 @@ program test_read_input_nml
   n = 1
   do
     read(1, '(A)', iostat=stat) line
-    if (stat.eq.-1) then
+    if (stat < 0) then
```
Comment (bensonr) [inline test_fms/mpp/test_read_input_nml.F90:71]: You should use the _is_iostat_end_ function that came in with the 2003 standard for testing the status code.

**Review by thomas-robinson — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Review by rem1776 — APPROVED** [review]
