### PR TITLE
Diag_manager: Leap day fix

### LINKED ISSUE #1471: Error on the leap day time increment
**Describe the bug**
Today two UFS applications RRFSv1 and AQMv7 parallel runs failed with the same error message:
```
FATAL from PE  2713: diag_manager_mod::register_diag_field:  file=fv3_history: Invalid date. Date=2025-02-29 00:00:00
```
The tests failed for both "julian" and "gregorian" calendar type. Both runs have the following in the diag_table:

```
20240229.06Z.C793.32bit.non-hydro.regional
2024 02 29 06 00 00

"fv3_history",             1,  "years",   1, "hours", "time"
"fv3_history2d",           1,  "years",   1, "hours", "time"
...
```

After changing the two lines with file names to:
```
"fv3_history",             1,  "hours",   1, "hours", "time"
"fv3_history2d",           1,  "hours",   1, "hours", "time"
```
Both tests ran successfully. It looks to me that the time increment "1 year" for the leap day 20240229 is not correctly computed. 

**To Reproduce**
Run a test with 20240229 ICs with diag_table above.

**Expected behavior**
The model should not failed with error of wrong date: 20250229. The time manager should give 20250228 for a 1 year increment.

**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Type and version [e.g. Intel 19.1]
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**

implement a hack for when starting with 2/29 and outputting yearly data

This solves the problem for both the old and the new diag_manager. The PR is for dmUpdate because `diag_time_inc` was moved to the new module `fms_diag_time_utils_mod`

Fixes #1471 

**How Has This Been Tested?**
CI

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: diag_manager/fms_diag_time_utils.F90 [hunk 1]
```diff
@@ -180,7 +187,17 @@ TYPE(time_type) FUNCTION diag_forecast_time_inc(time, output_freq, output_units,
        IF ( get_calendar_type() == NO_CALENDAR ) THEN
           error_message_local = 'output units of years NOT allowed with no calendar'
        ELSE
+        call get_date(Time, cyear, cmonth, cday, chour, cmin, csecond)
+        if (cmonth .eq. 2 .and. cday .eq. 29) then
+          !! TODO this is a hack, the leap year issue should be fixed inside increment_date instead
+          !! increment_date should also be updated to work in cases like when the frequency is 1 month and you
+          !! are starting from 1/31
```
Comment (uramirez8707) [inline diag_manager/fms_diag_time_utils.F90:194]: @mlee03

**Review by rem1776 — APPROVED** [review]
