### PR TITLE
Data_override[2]: get_grid fix 

### LINKED ISSUE #589: Data_override[2] - crash in get_grid_version_1
**Describe the bug**
In [get_grid_version_1](https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/data_override/data_override.F90#L1283), the variable `siz` is defined with a size of 4. 

https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/data_override/data_override.F90#L1291

Then, later on the code calls `get_variable_size`
https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/data_override/data_override.F90#L1323

In `get_variable_size`, if the buffer sent in (in this case `siz`) is not the same size as in the netcdf file the code will crash `(4 != 2)`: 
https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/fms2_io/netcdf_io.F90#L1457-L1459

**To Reproduce**
This bug was discovered when running  the SCM model, but it can be reproduced when using a grid_spec.nc file that has the axis data in it (as opposed to the grid_spec.nc file pointing to other files and those files have the axis data in this case `get_grid_version_2` will be called, which is what is normally used) 

**Expected behavior**
The `get_variable_size` calls need to be modified so the buffer is the same size as the variable in the netcdf file.
 
**System Environment**
This happens in any system.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This PR: 
1. Ensures that the buffer send in to a `get_variable_size` has the correct dimensions. 
2. Adds the following to avoid seg faults since `grid_center_bug` is an optional argument. 
``` F90
      if (present(grid_center_bug)) then
          gc_bug = grid_center_bug
      else
          gc_bug = .false.
      endif
```
3. Adds a unit test to test the functionality of `get_grid_version_1`. 

Fixes #589 

**How Has This Been Tested?**
`make check` passes on skylake with intel20 and on travis 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: test_fms/data_override/test_get_grid_v1.F90 [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+   err = nf90_def_var(ncid, 'geolon_vert_t', nf90_double, (/dimid3,dimid4/), varid3)
+   err = nf90_def_var(ncid, 'geolat_vert_t', nf90_double, (/dimid3,dimid4/), varid4)
+   err = nf90_def_var(ncid, 'geolon_t',  nf90_double, (/dimid3,dimid4/), varid5)
+
+   err = nf90_enddef(ncid)
+   err = nf90_put_var(ncid, varid1, lon_in(1))
+   err = nf90_put_var(ncid, varid2, lat_in(1))
+   err = nf90_close(ncid)
+endif
+
```
Comment (uramirez8707) [inline test_fms/data_override/test_get_grid_v1.F90:77]: Sync is needed here

File: test_fms/data_override/test_get_grid_v1.F90 [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+   err = nf90_def_var(ncid, 'x_vert_T', nf90_double, (/dimid1, dimid2, dimid3/), varid2)
+   err = nf90_def_var(ncid, 'y_vert_T', nf90_double, (/dimid1, dimid2, dimid3/), varid3)
+
+   err = nf90_enddef(ncid)
+   err = nf90_put_var(ncid, varid2, lon_vert_in)
+   err = nf90_put_var(ncid, varid3, lat_vert_in)
+
+   err = nf90_close(ncid)
+endif
+call get_grid_version_1("grid_spec.nc", "ocn", Domain, is, ie, js, je, lon, lat, &
```
Comment (uramirez8707) [inline test_fms/data_override/test_get_grid_v1.F90:124]: Sync is needed here

**Review by thomas-robinson — APPROVED** [review]

**Comment by thomas-robinson** [comment]
@GFDL-Eric please review this code, then I will merge it.
