### PR TITLE
Modify`diag_field_add_attribute` to accept r4 and r8

### LINKED ISSUE #1621: Help with mixed-precision FMS (in GEOS)
In GEOS, we've always done rather crazy things to support our use of FMS because we build our FV3 core at r4 but MOM6 requires r8. So we've built both fms_r4 and fms_r8 and then done CMake include and link shenanigans to get things working.

Since FMS has been working on mixed-precision support, I decided to try it out with GEOS. And I hit a build issue but I'm not sure if it's "You built FMS wrong" or "An interface is missing". I'm suspecting the latter, but it can easily be the former.[^1]

First, I built FMS using (less the netcdf bits):
```cmake
-D32BIT=ON -DFPIC=ON -DCONSTANTS=GEOS -DUSE_DEPRECATED_IO=ON
```
and that gave me a libfms_r4 library. This seemed to be what I want to do, right?

If so, when I go to build GEOS I get:
```
[  0%] Building Fortran object src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/@GEOS_OceanGridComp/MOM6_GEOSPlug/mom6_cmake/CMakeFiles/mom6.dir/__/@mom6/config_src/infra/FMS2/MOM_diag_manager_infra.F90.o
/Users/mathomp4/Models/GEOSgcm-v12-FMSMixedPrec/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/@GEOS_OceanGridComp/MOM6_GEOSPlug/@mom6/config_src/infra/FMS2/MOM_diag_manager_infra.F90:444:71:

  444 |   call FMS_diag_field_add_attribute(diag_field_id, att_name, att_value)
      |                                                                       1
Error: There is no specific subroutine for the generic 'diag_field_add_attribute' at (1)
/Users/mathomp4/Models/GEOSgcm-v12-FMSMixedPrec/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/@GEOS_OceanGridComp/MOM6_GEOSPlug/@mom6/config_src/infra/FMS2/MOM_diag_manager_infra.F90:414:71:

  414 |   call FMS_diag_field_add_attribute(diag_field_id, att_name, att_value)
      |                                                                       1
Error: There is no specific subroutine for the generic 'diag_field_add_attribute' at (1)
```

Now, since I compile MOM6 as r8, then everything going into that routine would be r8 as well and from my reading of that routine in FMS:

https://github.com/NOAA-GFDL/FMS/blob/899ea6e2fee06fb2a3cc52291e1e01a5313b283c/diag_manager/diag_manager.F90#L369-L377

is that it doesn't have r4 and r8 variants of the real routines. But again, I might be building wrong.

Any advice/criticism is greatly appreciated.

[^1]: It could also be "You are building MOM6 wrong" as well. I see they have an `OVERLOAD_R8` in [MOM_diag_manager_infra.F90](https://github.com/GEOS-ESM/MOM6/blob/ce58a328874fdfa8d34819d23b05d7a669d9fb4b/config_src/infra/FMS2/MOM_diag_manager_infra.F90#L41), but since we are explicitly compiling at r8, that wouldn't be necessary. (I did try it and got an ambiguous interface as expected.)

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
Modifies `diag_field_add_attribute` to accept r4 and r8
Adds a test

Fixes #1621 

**How Has This Been Tested?**
CI including new test

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: diag_manager/diag_manager.F90 [hunk 1]
```diff
@@ -4561,6 +4558,46 @@ SUBROUTINE diag_field_add_attribute_i1d(diag_field_id, att_name, att_value)
...
+    INTEGER,          INTENT(in) :: diag_field_id !< ID number for field to add attribute to
+    CHARACTER(len=*), INTENT(in) :: att_name      !< new attribute name
+    class(*),         INTENT(in) :: att_value     !< new attribute value
+
+    select type(att_value)
+    type is (real(kind=r4_kind))
+      call diag_field_add_attribute_scalar_r(diag_field_id, att_name, real(att_value))
+    type is (real(kind=r8_kind))
+      call diag_field_add_attribute_scalar_r(diag_field_id, att_name, real(att_value))
+    type is (integer(kind=i4_kind))
```
[the remark this answers is not in the document]
Comment (uramirez8707) [reply diag_manager/diag_manager.F90]: In the old diag manager, it ends up always writing the att_value as NF90_FLOAT. 
https://github.com/NOAA-GFDL/FMS/blob/d79c3b53c04e81ba009533aa3f6428d102868432/diag_manager/diag_manager.F90#L4547
In https://github.com/NOAA-GFDL/FMS/pull/1625/commits/4829fe88739cde63cbb349320b020062b3f74225, I made the changes so that the new diag manager uses the actual precision of att_value.

**Review by bensonr — APPROVED** [review]

File: diag_manager/diag_manager.F90 [hunk 2]
```diff
@@ -4496,70 +4493,66 @@ SUBROUTINE diag_field_attribute_init(diag_field_id, name, type, cval, ival, rval
...
+         call mpp_error(FATAL, "Diag_field_add_attribute 0d:: unsupported type. The acceptable types "//&
+                            "are float, double, integer, and string")
+      end select
     else
-      CALL diag_field_attribute_init(diag_field_id, att_name, NF90_CHAR, cval=att_value)
+      select type(att_value)
+      type is (real(kind=r4_kind))
+         CALL diag_field_attribute_init(diag_field_id, att_name, NF90_FLOAT, rval=real((/att_value/)))
+      type is (real(kind=r8_kind))
+         CALL diag_field_attribute_init(diag_field_id, att_name, NF90_FLOAT, rval=real((/att_value/)))
```
Comment (mathomp4) [inline diag_manager/diag_manager.F90:4521]: If a r8 value is coming in, shouldn't this be an [`NF90_DOUBLE`](https://docs.unidata.ucar.edu/netcdf-fortran/current/f90-variables.html#f90-language-types-corresponding-to-netcdf-external-data-types) in both?

Comment (mathomp4) [reply diag_manager/diag_manager.F90:4521]: In both routines, not both lines, that is.
