### PR TITLE
MODERN_DIAG_MANAGER: fix error when setting zbounds for more than one variable

### LINKED ISSUE #1812: BUG - MODERN_DIAG_MANAGER: error when setting zbounds for more than one variable
**Describe the bug**
As reported by @GFDL-Eric 

If you are defining zbounds for more than one variable (with a different zaxis dimension name) in a diag_file causes the error
```
FATAL from PE   768: NetCDF: Invalid dimension ID or name
```

**To Reproduce**
The error can be reproduce using this updated test:
https://github.com/uramirez8707/FMS/blob/b928fac2795a1e12cd037094c8c2ec69665c2917/test_fms/diag_manager/test_multiple_zbounds.sh#L26-L55

https://github.com/uramirez8707/FMS/actions/runs/20579020712/job/59102345630

**Expected behavior**
You should be able to define zbounds for multiple variables

**System Environment**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
Fixes #1812 
This PR includes two fixes to be able to support setting zbounds for more than one variable

1.  This is only checking if the zbounds are the same. It should also be checking for the parent_axis_id. https://github.com/NOAA-GFDL/FMS/blob/59763e905da2c855a753e2350c83017bde357295/diag_manager/fms_diag_axis_object.F90#L1456-L1467
2. The dimension name is hard codded incorrectly: https://github.com/NOAA-GFDL/FMS/blob/59763e905da2c855a753e2350c83017bde357295/diag_manager/fms_diag_field_object.F90#L1196

**How Has This Been Tested?**
CI, including the new test

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

File: diag_manager/fms_diag_axis_object.F90 [hunk 1]
```diff
@@ -934,6 +935,19 @@ function get_compute_indices(this) result(indx)
...
+  !! @return .True. if the zbounds are the same
+  function is_same_zbounds(this, zbounds) result(is_same)
+    class(fmsDiagSubAxis_type), intent(in) :: this       !< diag_sub_axis object
+    real(kind=r4_kind),         intent(in) :: zbounds(2) !< zbounds to compare with
+    logical :: is_same
+
+    is_same = .false.
+    if (zbounds(1) .eq. this%zbounds(1) .and. zbounds(2) .eq. this%zbounds(2)) then
+      is_same = .true.
+    endif
```
Comment (rem1776) [inline diag_manager/fms_diag_axis_object.F90]:
```suggestion
    is_same = zbounds(1) .eq. this%zbounds(1) .and. zbounds(2) .eq. this%zbounds(2)
```

File: diag_manager/fms_diag_axis_object.F90 [hunk 2]
```diff
@@ -1451,52 +1465,57 @@ subroutine create_new_z_subaxis(zbounds, var_axis_ids, diag_axis, naxis, file_ax
...
+    !< Determine which axis is the z axis:
+    do i = 1, size(var_axis_ids)
+      select type (parent_axis => diag_axis(var_axis_ids(i))%axis)
+      type is (fmsDiagFullAxis_type)
+        if (parent_axis%cart_name .eq. "Z") then
+          parent_axis_id = var_axis_ids(i)
+          zaxis_index = i
+        endif
+      end select
+    enddo
```
Comment (rem1776) [inline diag_manager/fms_diag_axis_object.F90:1484]: Might be good to check if this loop actually hits the conditional in case theres not a pre-existing z axis.

File: diag_manager/fms_diag_axis_object.F90 [hunk 3]
```diff
@@ -1517,6 +1536,32 @@ function is_parent_axis(axis_id, parent_axis_id, diag_axis) &
...
+      type is (fmsDiagSubAxis_type)
+        if (axis_ptr%parent_axis_id .eq. parent_axis_id) then
+          if (axis_ptr%is_same_zbounds(field_yaml%get_var_zbounds())) then
+            dim_name = axis_ptr%subaxis_name
+            return
+          endif
+        endif
+      end select
+    enddo
+    dim_name = ""
```
Comment (rem1776) [inline diag_manager/fms_diag_axis_object.F90]: Can the dimension name be empty or should this error out instead?

File: diag_manager/fms_diag_axis_object.F90 (hunk 1 above)
Comment (uramirez8707) [reply diag_manager/fms_diag_axis_object.F90]: Yes, so much better :)

File: diag_manager/fms_diag_axis_object.F90 (hunk 3 above)
Comment (uramirez8707) [reply diag_manager/fms_diag_axis_object.F90]: You are right, it should just error out.

File: diag_manager/fms_diag_axis_object.F90 (hunk 2 above)
Comment (uramirez8707) [reply diag_manager/fms_diag_axis_object.F90:1484]: Good idea! I will add a FATAL.
