### PR TITLE
Interpolator cleanup

### LINKED ISSUE #418: Interpolator compiler warnings
**Describe the bug**
If I compile FMS and turn on all the warnings :) I get the following warnings when it is compiling interpolator.  
```
interpolator.F90(3392): remark #7712: This variable has not been used.   [TWEIGHT]
real :: tweight, tweight1, tweight2, tweight3
--------^
interpolator.F90(3258): remark #7712: This variable has not been used.   [TWEIGHT]
real :: tweight      !< No description
--------^
interpolator.F90(3392): remark #7712: This variable has not been used.   [TWEIGHT1]
real :: tweight, tweight1, tweight2, tweight3
-----------------^
interpolator.F90(3259): remark #7712: This variable has not been used.   [TWEIGHT1]
real :: tweight1     !< The time weight between the climatology years
--------^
interpolator.F90(3392): remark #7712: This variable has not been used.   [TWEIGHT2]
real :: tweight, tweight1, tweight2, tweight3
---------------------------^
interpolator.F90(3260): remark #7712: This variable has not been used.   [TWEIGHT2]
real :: tweight2     !< No description
--------^
interpolator.F90(3392): remark #7712: This variable has not been used.   [TWEIGHT3]
real :: tweight, tweight1, tweight2, tweight3
-------------------------------------^
interpolator.F90(3261): remark #7712: This variable has not been used.   [TWEIGHT3]
real :: tweight3     !< The time weight between the months
--------^
interpolator.F90(483): remark #7712: This variable has not been used.   [UNIT]
integer                      :: unit
--------------------------------^
interpolator.F90(489): remark #7712: This variable has not been used.   [NAME_PRESENT]
logical                      :: NAME_PRESENT
--------------------------------^
interpolator.F90(3399): remark #7712: This variable has not been used.   [J]
integer :: j, k, i, n
-----------^
interpolator.F90(3399): remark #7712: This variable has not been used.   [N]
integer :: j, k, i, n
--------------------^
interpolator.F90(3269): remark #7712: This variable has not been used.   [N]
integer :: i, j, k, n                    !< No description
--------------------^
interpolator.F90(3399): remark #7712: This variable has not been used.   [K]
integer :: j, k, i, n
--------------^
interpolator.F90(3393): remark #7712: This variable has not been used.   [TAUM]
integer :: taum, taup, ilon
-----------^
interpolator.F90(3262): remark #7712: This variable has not been used.   [TAUM]
integer :: taum, taup, ilon          !< No description
-----------^
interpolator.F90(3393): remark #7712: This variable has not been used.   [TAUP]
integer :: taum, taup, ilon
-----------------^
interpolator.F90(3262): remark #7712: This variable has not been used.   [TAUP]
integer :: taum, taup, ilon          !< No description
-----------------^
interpolator.F90(3393): remark #7712: This variable has not been used.   [ILON]
integer :: taum, taup, ilon
-----------------------^
interpolator.F90(3395): remark #7712: This variable has not been used.   [P_FACT]
real :: p_fact(size(interp_data,1),size(interp_data,2))
--------^
interpolator.F90(3397): remark #7712: This variable has not been used.   [RESULT]
logical :: result
-----------^
interpolator.F90(3267): remark #7712: This variable has not been used.   [RESULT]
logical :: result                         !< No description
-----------^
interpolator.F90(3097): remark #7712: This variable has not been used.   [RESULT]
logical :: result
```
**To Reproduce**
compile FMS with the `-warn all` flag 

**Expected behavior**
We shouldn't get any warnings, especially is they are easy to solve. 

**System Environment**
Describe the system environment, include:
This happens in any system 

**Additional context**
Other subroutines have similar errors. I am only focusing on interpolator because I am already poking at it to solve #404

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This PR:

1.  Removes any unused variables
2. Removes `#include<file_version.h>`  and `#include <fms_platform.h>` because all they do is mess up the lines in the debugger and are not really needed ...

Fixes #418 

This is just some clean up before pushing my fix to issue #404 

**How Has This Been Tested?**
Passes make distcheck in travis. 
Tried AM4.1 with intel, debug/prod openmp, c4 and it still works ...

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: interpolator/interpolator.F90 [hunk 1]
```diff
@@ -1173,11 +1164,6 @@ subroutine interpolator_init( clim_type, file_name, lonb_mod, latb_mod, &
 
 module_is_initialized = .true.
 
-!---------------------------------------------------------------------
-!    write version number and namelist to logfile.
-!---------------------------------------------------------------------
-call write_version_number("INTERPOLATOR_MOD", version)
-
```
Comment (thomas-robinson) [inline interpolator/interpolator.F90:1180]: I'm not sure a decision has been made to remove this.

File: interpolator/interpolator.F90 [hunk 2]
```diff
@@ -80,8 +80,6 @@
 !! </table>
 module interpolator_mod
 
-#include <fms_platform.h>
```
Comment (thomas-robinson) [inline interpolator/interpolator.F90:83]: It's difficult to tell from just a review that this is safe.  My inclination is that it is safe because of #374  but you make need to `use platform_mod` .  Did you make sure none of the other stuff in fms_platform.h` is being used?

File: interpolator/interpolator.F90 (hunk 1 above)
Comment (uramirez8707) [reply interpolator/interpolator.F90:1180]: Ok. I'll put it back.

File: interpolator/interpolator.F90 (hunk 2 above)
Comment (uramirez8707) [reply interpolator/interpolator.F90:83]: Yes, I check and interpolator doesn't use any of the other stuff in `fms_platform.h`.

File: interpolator/interpolator.F90 (hunk 1 above)
Comment (thomas-robinson) [reply interpolator/interpolator.F90]: Was it decided to remove this?  Now I don't remember, and it doesn't look like you put it back...

Comment (uramirez8707) [reply interpolator/interpolator.F90]: I don't think so. 

I put it back in https://github.com/NOAA-GFDL/FMS/pull/419/commits/bf63e86e60a3457563367446234ebcdc8b45ffbb
