### PR TITLE
Fix quad precision issue with hard on/off switch

### LINKED ISSUE #186: Use of wrong abs function in C sources
Some of the C source files use the wrong version of `abs` for the variable type of the variables acted on.

### LINKED ISSUE #214: quad precision default behavior changed in xanadu
The default behavior of enabling quad precision changed from in the xanadu release.  Prior to xanadu, the macro NO_QUAD_PRECISION was not defined by default.  With xanadu the macro is defined by default, unless one adds an additional macro at compile time (-DQUAD_PRECISION) with the further assumption you are not using PGI compilers.

The proposal is to revert to pre-xanadu behavior and ensure NO_QUAD_PRECISION is undefined by default.

### PR DESCRIPTION
**Pull request by bensonr**
---
name: Pull Request
about: Create a pull request to help us improve
title: Fix quad precision issue with hard on/off switch
labels: ''
---

**Description**
The original logic (pre July 2018) was setting behavior with a heuristic test and delivered different behavior on different platforms by default.  However the original logic fix (July 2018) changed defaults on non-Cray platforms.  The attempt to fix the logic in Nov 2019 changed default behavior on certain Cray platforms.  This update does away with heuristic attempts to define behavior and implements a hard on/off switch.

Fixes #186
Fixes #214

**How Has This Been Tested?**
Tests were not run prior to PR.  Relying upon code review for these macro changes.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

File: include/fms_platform.h [hunk 1]
```diff
@@ -107,13 +107,13 @@ use,intrinsic :: iso_c_binding, only: c_double,c_float,c_int64_t, &
...
-#if defined(QUAD_PRECISION) && defined(__PGI)
-#error "cannot define QUAD_PRECISION and use PGI compiler"
-#elif !defined(QUAD_PRECISION) && defined(__PGI)
+! The NO_QUAD_PRECISION macro will be deprecated and removed at some future time.
+! Model code will rely solely upon the ENABLE_QUAD_PRECISION macro thereafer.
+#if defined(ENABLE_QUAD_PRECISION) 
+#undef NO_QUAD_PRECISION
+#else
 #define NO_QUAD_PRECISION
 #define QUAD_KIND DOUBLE_KIND
```
Comment (underwoo) [inline include/fms_platform.h]: Please add

```suggestion
#undef QUAD_KIND
#define QUAD_KIND DOUBLE_KIND
```
